spring:
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
  datasource:
    url: jdbc:postgresql://localhost:5432/pessoa_db?useSSL=false
    username: root
    password: root
server:
  port: 8080
  address: localhost
management:
  server:
    port: 9001
    address: localhost
